package com.example.abmotorss.navigation

const val HOME_URL = "home"
const val LOGIN_URL = "login"
const val SIGNUP_URL = "signup"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val SPLASH_URL = "splashscreen"
const val ABOUT_URL = "about"
const val BM_URL = "bmScreen"
const val FORD_URL = "fordScreen"
const val LEX_URL = "lexscreen"
const val MERC_URL = "mercscreen"
const val MIT_URL = "mitscreen"
const val TOY_URL = "toyscreen"
const val LAND_URL = "toyscreen"
const val SUB_URL = "subscreen"
const val NISS_URL = "nissscreen"
const val ISU_URL = "isuscreen"
const val JEEP_URL = "jeepscreen"
const val AUDI_URL = "audiscreen"
